### ISSUE TITLE
Syntax highlighting for NppExec script code

### ISSUE THREAD

**Issue by dinkumoil** [d0vgan/nppexec#21]
I'm a heavy user of your plugin, so at first I want to say thank you for this useful piece of software.

I created a UDL to add syntax highlighting of NppExec script code, see [this Gist](https://gist.github.com/dinkumoil/2cb3989d318350d7f0c8c774e2b50200). Feel free to use, link to or even distribute it with your plugin.

However, syntax highlighting would be better if it would be possible to precede the target label after a `goto` command with a colon. 

For example, instead of writing

`goto Label`

it would be nice to be able to write

`goto :Label`

This way `:Label` would be highlighted the same way like the target label itself which would enhance code readability.

So, I would like to make a feature request, to be able to write `goto Label` or `goto :Label`. **Please note:** Setting the standard colors of the UDL to the same colors like labels is not an option, because this would also affect literal strings.

Here is a screenshot of a syntax-highlighted NppExec script using my UDL file. Missing highlighting of target labels is emphasized.

![grafik](https://user-images.githubusercontent.com/24699812/92333213-32643a00-f084-11ea-9d98-abe6b0b573ca.png)

**Comment by d0vgan** [comment]
This syntax highlighting is very good!
Please try the latest dev version of NppExec from
https://sourceforge.net/projects/npp-plugins/files/NppExec/NppExec%20Plugin%20v0.6%20RC3-RC4%20%28dev%29/

**Comment by d0vgan** [comment]
Looks like the syntax file needs to be updated further as NppExec v0.6 RC4 will add a few more keywords and environment variables :)
See "doc\NppExec\NppExec.txt" for details.

**Comment by dinkumoil** [comment]
@d0vgan Thank you for already including the `goto :label` notation! I have updated the Gist with my UDL.

For testing purposes I've opened the files `NppExec.txt` and `NppExec_HelpAll.txt` with Notepad++ and activated highlighting with my UDL. Of course, it its not perfect but I think it's good enough.

However, I didn't find a documentation concerning math functions. In a piece of sample code in `NppExec_HelpAll.txt` I found the `trunc` function, thus I guess you've included more math stuff into your plugin. Would you mind to add documentation for that?

Additionally, I found the constants `wm_close` and `wmclose` in some sample code in `NppExec_HelpAll.txt`. Does your plugin know more of these Windows messages? If yes, please provide some documentation about that.

**Comment by dinkumoil** [comment]
An additional feature request: Would you mind to support the language constants `L_TEXT`, `L_PHP`, ... `L_EXTERNAL` in NppExec scripts? I have already included them into my UDL but I noticed that it is not possible to use them (tested with newest 64 bit version of NppExec v.06 RC4).

**Comment by d0vgan** [comment]
The math functions are handled by the third-party library Function Parser (fparser). Its documentation is located under "doc\NppExec\fparser.html", section "The function string syntax".
Maybe I should consider including "fparser.html" in the NppExec Manual? Or try to reference it from the NppExec Manual as an external .html file using the mad technique described in https://docs.microsoft.com/en-us/previous-versions/windows/desktop/htmlhelp/example--link-to-a-file-outside-of-your-help-system ? I am not sure.

The "wm_close" and "wmclose" in "NppExec_HelpAll.txt" are possible parameters of the PROC_SIGNAL command, in the same way as "ctrl-c" and "ctrl-break".

All the constants related to Notepad++, Scintilla and WinAPI are read from the *.h files under "Notepad++\plugins\NppExec\NppExec". NppExec uses a simple parser that reads every line that starts with "#define" and ignore everything else in these files. So it does not understand L_TEXT, L_PHP etc. because they are part of "enum" rather than a "#define". Parsing the "enum" structure does not look like an easy task because members of an "enum" may be assigned to some values, as well as may reference other values of the same "enum", e.g.: "enum MyEnum { First = 1, Second, Tenth = 10, Total = (First+Second+Tenth) };". I don't want to implement a generic parser for the "enum" structure.

**Comment by dinkumoil** [comment]
Thank you for your explanations. I will include the math functions and missing operators in my UDL.

Regarding enum parser: I don't think we need a generic enum parser, since the `LangType` enum presumeably will never contain any computations (why should it?). And I think it will never contain assignments of fix values to some of its members as well. New languages are simply added to its end (or, to be exact, inserted before the `L_EXTERNAL` member). So, the task to parse the `LangType` enum is much simpler. But it is up to you, I'm not a C++ dev and can not do this change, but it would be nice to have.

**Comment by dinkumoil** [comment]
[Gist with NppExec UDL](https://gist.github.com/dinkumoil/2cb3989d318350d7f0c8c774e2b50200) has been updated.

**Comment by d0vgan** [comment]
And now the latest NppExec20200914 supports "enum { ... }" definitions! I became intrigued by implementing the parsing of the "enum" structure - and implemented it.

**Comment by dinkumoil** [comment]
Thank you! Tested and works.

So, I think this issue can be closed.
