### ISSUE TITLE
[Enhancement] Option to specify the name/extension of the file containing NppExec scripts

### ISSUE THREAD

**Issue by pidgeon777** [d0vgan/nppexec#25]
Actually, the file containing the NppExec scripts is:

`npes_saved.txt`

Adding an option to specify at least the extension of that file would have two big consequences if editing that file inside Notepad++:

1.  Automatic syntax scheme: Notepad++ would automatically recognize the syntax for the NppExec script file based on its extension.
2.  Ability to parse the script file: many parsers exist (SourceCookifier, etc.) and adding a custom extension to the NppExec script file would permit those parsers to enable the correct parsing set according to the file extension. Useful for example for browsing labels, functions, variables etc.

Txt extension is too generic and by specifying a custom extension, the benefits listed above would be guaranteed.

Another really simple option could be replacing the `npes_saved.txt` format with a new one such as `npes_saved.npe`.

**Comment by dinkumoil** [comment]
To get automatic syntax highlighting for _NppExec_ script code you can use the following workaround:

1. Install [_NppEventExec_](https://github.com/MIvanchev/NppEventExec) plugin.
2. Navigate to `(menu) Plugins -> NppEventExec -> Edit rules`. In the dialog box popping up, click the _Add a new rule_ sidebar button.
3. Configure a rule as shown in the following picture: 
![grafik](https://user-images.githubusercontent.com/24699812/95459515-10582300-0974-11eb-8278-8a0817d176ad.png)
4. Close the dialog by clicking _Apply_ and in the main dialog click _Save_.
5. Open your _NppExec_'s `npes_saved.txt` file.
6. Add the following code to it:
```
::NppExecSyntaxHighlighting
npp_console keep
npp_menucommand Language/NppExec
npp_sendmsg NPPM_GETFULLCURRENTPATH 1024 @""
npp_sendmsg NPPM_DOOPEN 0 "$(MSG_LPARAM)"
```
**Please note:** Since the parameters of the `npp_menucommand` must be localized, you have to adapt line 3 of the code above to your Notepad++ locale (the word `Language`, i.e. name of the language menu) and to the name you assigned to your _NppExec_ user defined language in UDL dialog (the word `NppExec`).

After restarting Notepad++, if you open your `npes_saved.txt` file it will be syntax-highlighted and the function list panel will show its structure (if you also have imported my function list enhancement I pointed you to in https://github.com/d0vgan/nppexec/issues/22#issuecomment-705523942). 

**Small flaw:** When Notepad++ doesn't run already and you open your `npes_saved.txt` file by Notepad++'s entry in Windows Explorer context menu, syntax highlighting will not work. This seems to be a bug in Notepad++ itself (it doesn't fire the `NPPN_FILEOPENED` event or doesn't handle the `npp_menucommand Language/NppExec` command) or in _NppEventExec_ plugin (it doesn't handle the event in that early state of Notepad++ startup).

**Comment by pidgeon777** [comment]
Nice workaround, indeed.

It has the advantage to be customizable, but in my opinion it has two disadvantages:
1. It needs an external plugin to be installed
2. Still doesn't make npes_saved.txt easily parseable by tags generations tools (SourceCookifier), which heavily rely on file extensions to correctly apply the proper parsing schemes.

Another option, as an alternative to the one you suggested, could be to create a LuaScript script for Notepad++ through this great plugin, which I highly suggest:

https://github.com/dail8859/LuaScript

Even more customizable.

But, in my opinion, offering a chance to specify at least the extension used for the NppExec npes_saved script file would be preferable, for the reasons I specified above.

**Comment by d0vgan** [comment]
I still don't have a final opinion regarding this.
On the one hand, it makes sense to use some specific file extension.
On the other hand, there are few reasons to not do this:
1) NppExec's scripts are saved as a plain text file, and the .txt extension reflects this fact
2) Backwards-compatibility: I know at least one plugin that reads the file "npes_saved.txt" directly
3) To edit the saved scripts in Notepad++, one may use a simple NppExec's script such as:
```
// edit NppExec's saved scripts
npp_open "$(PLUGINS_CONFIG_DIR)\npes_saved.txt"
npp_menucommand Language\\NppExec
```

**Comment by pidgeon777** [comment]
What about giving the user an option to specify at least the npes_saved file extension? Maybe thanks to a hidden advanced configuration file (if exists), or though the GUI eventually warning about the possible incompatibility of other plugins due to the extension change.

Maybe it would be possible to release a beta DLL just to try it out?

**Comment by artie-finkelstein** [comment]
I use the "mklink" command or the "Link Shell Extension" program to create a hardlink from npes_saved.txt to startup.npes.  (Chosen to mimic the convention used by both LuaScript and PythonScript) 

All my scripts are written using the .npes file extension.  I have installed the wonderful UDL lexer from 'dinkumoil' in ...\userDefineLangs and a modified version of his language parser 'nppexec.xml' in ...\functionList (I commented out all 'class' statements which results in a FunctionList display that emulates that of a standard batch file, i.e., all the labels show up).  

I also added an .npes entry to the registry so I could enable a 'PerceivedType' of 'text' to enable viewing the file contents in the Explorer preview pane.

The one downside is that if I copy the entire Notepad++ installation tree to a new location, the linking is lost and the new tree needs to be tweaked back into shape (I need to recreate the link from npes_saved.txt to startup.npes).  But that annoyance is more than offset by the automatic lexing, usable FunctionList and uniform naming conventions for scripting plugins.

**Comment by d0vgan** [comment]
https://github.com/d0vgan/nppexec/commit/7d625adcde4981412f047638c13a6796103ceabf

**Comment by artie-finkelstein** [comment]
Thank you.  I'm looking forward to having all the scripting engines I
use installed and configured in a similar manner.

**Comment by d0vgan** [comment]
https://community.notepad-plus-plus.org/topic/21365/nppexec-latest-development-version

**Comment by d0vgan** [comment]
https://github.com/d0vgan/nppexec/releases/tag/v07

**Comment by pidgeon777** [comment]
> All my scripts are written using the .npes file extension. I have installed the wonderful UDL lexer from 'dinkumoil' in ...\userDefineLangs and a modified version of his language parser 'nppexec.xml' in ...\functionList (I commented out all 'class' statements which results in a FunctionList display that emulates that of a standard batch file, i.e., all the labels show up).

Are those syntaxes / function list files available somewhere?

**Comment by dinkumoil** [comment]
@pidgeon777 

Have a look at [my repository](https://github.com/dinkumoil/ScriptCollection/tree/master/NppExec%20Development).
