### ISSUE TITLE
Causing other Notepad++ extension DLLs to get loaded twice?

### ISSUE THREAD

**Issue by Gitoffthelawn** [d0vgan/nppexec#47]
After installing NppExec v0.7, I was looking at some drive access logs.

After updating to v0.7, I noticed that other Notepad++ extension DLLs were being accessed differently than before updating NppExec.  They are now being read twice.  The new read operations have the pathnames in all capitals, whereas the original read operations were using mixed-case.

Any chance something changed in NppExec v0.7 that could cause this?

**Comment by d0vgan** [comment]
I am not sure. At least I believe there was no intentional change that might cause it. Could you do the following:
1. Close Notepad++
2. Go to Notepad++\plugins\NppExec and replace the existing NppExec.dll with NppExec.dll of version 0.6.2
3. Run Notepad++ and collect the drive access logs you mentioned
4. Close Notepad++
5. Go to Notepad++\plugins\NppExec and replace the existing NppExec.dll with NppExec.dll of version 0.7 (be sure to use the very same Notepad++ folder as the one used with NppExec.dll of version 0.6.2, it should not be a different copy of Notepad++ in another folder!)
6. Run Notepad++ and collect the drive access logs you mentioned
7. Compare the drive access logs collected for NppExec.dll version 0.6.2 and version 0.7 - if they are different, please share (attach) the drive access logs for both the cases.

**Comment by Gitoffthelawn** [comment]
"No intentional change" answers the primary question... thanks.

Regarding the testing, yes, I've added your instructions to my testing list.  There are over 50 items already on that list, so it could be a long while... but it's definitely on the list! :)

**Comment by d0vgan** [comment]
Is there any further information on this?

**Comment by Gitoffthelawn** [comment]
Hi. I got your message.  It's been a while, so I'll try to make some time to look at this for you.
