### ISSUE TITLE
[HTML docs] External links are not navigable

### ISSUE THREAD

**Issue by rdipardo** [d0vgan/nppexec#84]
It seems every current browser returns `ERR_BLOCKED_BY_RESPONSE` when trying to visit external links in a frame: [^1]

<img width="750" alt="no-nav-allowed-in-frame" src="https://github.com/d0vgan/nppexec/assets/59004801/c377ddd3-07bb-4d99-bdeb-19f030dc7d3c">

I would consider this a show-stopping defect for any public-facing website.

There is a client-side workaround, but it means injecting *another* script into every page, similar to this:

~~~js
window.addEventListener('DOMContentLoaded', function() {
  var links = document.getElementsByTagName('a')
  if (links.length) {
    // `links` is of type NodeList; make it a plain Array
    Array.prototype.slice.call(links).forEach(function(link) {
      // transform external links only
      if (link.protocol.indexOf('http') > -1 && link.pathname.indexOf('/NppExec_Manual') === -1) {
        link.href = "javascript:window.open('" + link.href + "', '_blank', 'noopener');"
      }
    })
  }
})
~~~

This will replace every hard-coded href with an inline script that opens the target in a new tab, not including internal links to other pages on the same host.

If acceptable, the fix can be implemented after #80 and #83 have been resolved. 

[^1]: Not including pages on the same host, obviously.

**Comment by d0vgan** [comment]
Alternative solution is to remove all hrefs for external links. In terms of the documentation, only the internal links are important. If someone wants to follow an external link, one can copy it and paste into another browser tab/window.
Or we must get rid of frames completely (since they seem to produce more problems than benefit) and use some different approach of having a vertical table of content on a page. The only reason why frames were used is because I simply do not other approach. For example, nppUserManual does not seem to use frames (but it's hard for me to understand what it uses instead).

**Comment by rdipardo** [comment]
> Alternative solution is to remove all hrefs for external links.

Or disable them. A few lines [of CSS][0] will do the job, e.g.

~~~css
a {
  pointer-events: none;
}
~~~

[0]: https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events

**Comment by d0vgan** [comment]
I've reworked the external links by using \<code\> tags for visual difference and removed the `href` links.
(Well, maybe there is a more suitable tag for this than \<code\>, maybe some form of styled text, but I'm not aware of.)
Idditionally I've added a couple of new sections to the Manual (and, correspondingly, to "toc.html").

**Comment by rdipardo** [comment]
Closing since this has been fixed in [`develop`](https://github.com/d0vgan/nppexec/tree/develop):

~~~sh-session
$ git grep -liE "<a.*href=\"(https?)" -- docs/NppExec_Manual || echo 'Clean!'

Clean!
~~~
