### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by KeyC0de** [d0vgan/nppexec#88]
There is absolutely no mention of a license for this plugin whatsoever.
What gives?

**Comment by d0vgan** [comment]
Each source file start with a comment saying
```
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
```
Do you want the same to be included in "NppExec.txt"?

**Comment by KeyC0de** [comment]
As far as I'm concerned, there should be at least a dedicated file, or a section in a manual, readme, wiki, doc w/e that talks about the license.
You didn't deem that necessary, ergo I will not tell you how to handle things.
You can close this issue.

**Comment by rdipardo** [comment]
@d0vgan 

> Do you want the same to be included in "NppExec.txt"?

I think this issue is more about the absence of a license icon on the project homepage, e.g.,

![repo-license-indicator](https://github.com/d0vgan/nppexec/assets/59004801/b14267e8-d6dc-42ac-a4c0-8b49c80c773d)

All this means is that GitHub's preferred [Ruby library](https://licensee.github.io/licensee/) can't identify the project's license from [a small list][0] of the most common ones:

```sh-session
$ licensee --remote https://github.com/d0vgan/nppexec
License:  None
```

The algorithm is pretty simple-minded. It basically does a file search for `COPYING`, `LICENSE` or similar, falling back to a `# License` heading in the Readme. Even then it's easily confused. For example, [here's a project][1] with a central `Copyright.txt` file that recites the MIT license verbatim. But since the author added some original text at the top, it's not purely verbatim enough for a positive match:

```sh-session
$ licensee --remote https://github.com/ppv/NPPFSIPlugin
License:        NOASSERTION
Matched files:  Copyright.txt
Copyright.txt:
  Content hash:  c2ef2bd3ce3f57889e55f07bfae386cbc7164be4
  License:       NOASSERTION
  Closest non-matching licenses:
    MIT similarity:    86.11%
    MIT-0 similarity:  67.20%
    NCSA similarity:   60.27%
```

I wouldn't worry about all of GitHub's little conventions; there's just too many to keep up with.

[0]: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#searching-github-by-license-type
[1]: https://github.com/ppv/NPPFSIPlugin

**Comment by d0vgan** [comment]
As the question had arisen, I've added a file "LICENSE" and updated the file "docs/NppExec.txt" to include a LICENSE section.
