### ISSUE TITLE
Does sci_sendmsg accept sParam?

### ISSUE THREAD

**Issue by mercurial-moon** [d0vgan/nppexec#95]
I recorded a macro in NPP for find and replace NBSP character the following is the XML

```
        <Macro name="Find and Replace NBSP" Ctrl="yes" Alt="no" Shift="yes" Key="112">
            <Action type="3" message="1700" wParam="0" lParam="0" sParam="" />
            <Action type="3" message="1601" wParam="0" lParam="0" sParam="\xa0" />
            <Action type="3" message="1625" wParam="0" lParam="1" sParam="" />
            <Action type="3" message="1602" wParam="0" lParam="0" sParam=" " />
            <Action type="3" message="1702" wParam="0" lParam="768" sParam="" />
            <Action type="3" message="1701" wParam="0" lParam="1609" sParam="" />
        </Macro>

```

when I try to do the same with `nppexec` it doesn't work
```
sci_sendmsg 1700 0 0 ""
sci_sendmsg 1601 0 0 "\xa0"
sci_sendmsg 1625 0 1 ""
sci_sendmsg 1602 0 0 " " 
sci_sendmsg 1702 0 768 ""
sci_sendmsg 1701 0 1609 ""
```
also the doc for `sci_sendmsg` doesn't say anything about `sparam` it says
```
sci_sendmsg <msg> <wparam> <lparam>  -  msg to Scintilla
```
Is sparam supported for `sci_sendmsg` or is there something wrong that I have done in the `nppexec` script?

**Comment by d0vgan** [comment]
Notepad++ saves its macros in Notepad++-specific format. The `message` parameter is most likely a Notepad++'s message (not a Scintialla's message) and the `sParam` seems to be either a character or a string, according to Notepad++'s source code. Anyway, the similarity between Notepad++'s macros and SendMessage's parameters is misleading, because Notepad++ has its own internal interpretation and processing of the macros. NppExec's commands `sci_sendmsg` and `npp_sendmsg` are just wrappers around WinAPI function `SendMessage`, they don't deal with macros.
If Notepad++'s header file "Notepad_plus_msgs.h" contained something similar to `NPPM_EXECUTEMACRO`, it probably would be possible to execute a macro by means of Notepad++.

**Comment by mercurial-moon** [comment]
Hi, in my macro, I had implemented... steps 1 and 2, step 3 was being done by nppexec with another command line program.
1. Find and Replace.
2. Copy to clipboard.
3. Send keys to an external program. (this pastes clipboard ..into another program)

I wanted to do all 3 steps sequentially in nppexec.
Would this be possible?

**Comment by d0vgan** [comment]
For text search & replace, you may look at the description and examples of `sci_find` and `sci_replace`:
```
help sci_find
help sci_replace
```
Copying to the clipboard is mentioned here:
https://d0vgan.github.io/nppexec/?q=4.6.11
and here:
https://d0vgan.github.io/nppexec/?q=4.6.8
